#!/usr/bin/env bash

protected_branch='main'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $1 != "staging" ] && [ "$protected_branch" != "$current_branch" ]
then
    echo "Don't push WIP branches to public GitHub! You're currently on $current_branch."
    exit 1
fi
